source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HYLogEngine_Example', :exclusive => true do
  pod 'HYLogEngine', :path => '../'
end

target 'HYLogEngine_Tests', :exclusive => true do
  pod 'HYLogEngine', :path => '../'

  
end
